### PR TITLE
adding vendor directory

### PR DESCRIPTION
**Pull request by enoodle**
This is a suggestion to move to the way Go 1.6 is handling vendoring. I just did:

```
mkdir vendor
cp -r Godeps/_workspace/src/* vendor/
```

I have seen this done in kubernetes too. I think we can keep the Godeps directory for a while and then remove it if we see that it works well for us.

@simon3z @pweil-

### CODE REVIEW

**Comment by simon3z** [comment]
> This is a suggestion to move to the way Go 1.6 is handling vendoring

Is this backward compatible with 1.4/1.5? (Can you build on those versions?)

**Comment by enoodle** [comment]
@simon3z This is not backward compatible but eventually we will have to do the change according to those warnings that I get while compiling using godep:
```
godep: WARNING: Godep workspaces (./Godeps/_workspace) are deprecated and support for them will be removed when go1.8 is released.
godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
```

To compile this way we just need to use:
```
go build cmd/image-inspector.go
```

**Comment by simon3z** [comment]
@enoodle we can't break builds on 1.4 and 1.5 just to suppress warnings in 1.6.
(Anyway I have the feeling that you can use this vendor path with 1.4 and 1.5 if you change the build configuration).

**Comment by enoodle** [comment]
@simon3z Can you please take another look at this? I think as we prepare for a new version of this tool we might be willing to let go of go1.4 to adopt the new "vendor/" directory and use better package management tools than Godep (which I personally really don't like, trying to add the github.com/containers/image repo as a dependency was a nightmare)

**Comment by simon3z** [comment]
@enoodle have you refreshed all the dependencies with newer versions?

**Comment by enoodle** [comment]
@simon3z No, I left them on the exact same version. You can see it in those files:
https://github.com/openshift/image-inspector/pull/20/files#diff-681659ab9abb4b4883e78e8aaa980dba ("Godeps/Godeps.json")
https://github.com/openshift/image-inspector/pull/20/files#diff-4061fcef378a6d912e14e2ce162a1995 ("vendor.conf")

**Comment by simon3z** [comment]
@enoodle as far as I understood by the conversation we just had you're still polishing this. Let me know when it's really settled.

**Comment by enoodle** [comment]
I see that kubernetes has started to move towards this, but I guess moving such a big project is harder. It is present in contianers/image [2] (They upgraded to a similar tool which is better because it does caching [3], I will try it out too). Openshift is also using the vendor directory but I couldn't find where it was introduced.

[1]https://github.com/kubernetes/kubernetes/pull/24242
[2]https://github.com/containers/image/pull/240
[3]https://github.com/containers/image/pull/244

**Comment by simon3z** [comment]
@ilackarms can you test / review this?
cc @pweil-

**Comment by ilackarms** [comment]
this compiles without issue, but i would suggest using `godep save` to generate  `Godeps` file and `vendor` directory rather than manually rearranging deprecated structure. 

To do so:
```
godep restore
rm -rf Godeps
godep save ./...
```

**Comment by enoodle** [comment]
@ilackarms Trash is similar to glide, it can also use the glide configuration file. I added a `make deps` line to the Dockerfile to do exactly what you advised, Thank you.

**Comment by enoodle** [comment]
ping @ilackarms @pweil- @simon3z Do you want to take another look? This make it much easier to manage dependencies.

**Comment by simon3z** [comment]
Moved to #57

**Pull request closed without merging**
