### PR TITLE
openscap to scan centos

### PR DESCRIPTION
**Pull request by enoodle**
This will identify centos based images as the equivalent RHEL and will scan them as RHEL system.

### CODE REVIEW

**Comment by enoodle** [comment]
@simon3z @ilackarms @pweil- please review

**Comment by simon3z** [comment]
Nice @enoodle, do we need tests for `getRHELDist`?

**Comment by enoodle** [comment]
@simon3z we have one [1] but I am not sure if it is important to updated it for this as it just a logic test and not e2e test.

[1]https://github.com/openshift/image-inspector/blob/master/pkg/openscap/openscap_test.go#L44

**Comment by simon3z** [comment]
@ilackarms @pweil- any time to review this?

**Comment by pweil-** [comment]
@simon3z the file will still be output in a RHEL naming format (`com.redhat.rhsa-RHEL%d.ds.xml.bz2`) if you're telling me that that's ok and the cve url naming convention is the same (and non-overlapping or unique) for RHEL/CentOS then I don't have any objections. It looks like those were the main places it was used.

**Comment by ilackarms** [comment]
i tested this change manually and appeared to work. however it would be nice to see an automated test for this change

**Comment by simon3z** [comment]
> i tested this change manually and appeared to work. however it would be nice to see an automated test for this change

@ilackarms any suggestion on how to achieve that?

**Comment by ilackarms** [comment]
@simon3z mock the client behavior (from manageiq or a generic consumer of the image inspector) in a test, similar to [tests for shared-secret authentication](https://github.com/ilackarms/image-inspector/blob/f81369e9dba9b4452ea375c30b114b5f7e93285e/pkg/inspector/image-inspector_ginkgo_test.go)

**Comment by simon3z** [comment]
@enoodle I think this should be brought up with a wider forum (please send an email about this).

**Comment by simon3z** [comment]
@enoodle AFAIK there is no CVE feed for CentOS. How do we expect this to work?

**Comment by simon3z** [comment]
> @enoodle AFAIK there is no CVE feed for CentOS. How do we expect this to work?

@enoodle any news?

**Comment by enoodle** [comment]
@simon3z I am not sure yet if this is possible, but I want to try to use [1] to allow scanning of different distributions. The current implementation is not the correct direction because the package names are different between rhel and centos.

[]1https://github.com/OpenSCAP/scap-security-guide

**Comment by simon3z** [comment]
> @simon3z I am not sure yet if this is possible, but I want to try to use [1] to allow scanning of different distributions. The current implementation is not the correct direction because the package names are different between rhel and centos.

@enoodle this is way much lower priority than all the other things we're working on.

**Pull request closed without merging**
