### PR TITLE
update github.com/fsouza/go-dockerclient to origin version

### PR DESCRIPTION
**Pull request by enoodle**
To get the RepoDigests in the image metadata

### CODE REVIEW

**Comment by simon3z** [comment]
@enoodle can we sync this with the version the OpenShift is using? (Just to make sure we're using something reliable enough).

**Comment by enoodle** [comment]
@simon3z I have now changed it to be the same version that they use in origin.

**Comment by simon3z** [comment]
@enoodle can you do your own build and verify that full feature in ManageIQ is working? (Please do a complete round of checks).

**Comment by enoodle** [comment]
@simon3z yes, I am working on this right now:
https://hub.docker.com/r/efreiber/image-inspector/builds/bkuvrv5zxxec5rhyulty4ce/

**Comment by simon3z** [comment]
@enoodle are you planning to have tests for RepoDigests? If so please handle them in another PR because this is impossible to review on GitHub.

**Comment by enoodle** [comment]
@simon3z I feel that it is part of the docker api so I didn't think of testing for its existence.

**Comment by simon3z** [comment]
@enoodle ok, thanks, please let me know when this is verified properly (full multiple cycles on ManageIQ, negative flows, failures, etc.) and I'll merge.

@pweil- do you want to review/ACK?

**Comment by enoodle** [comment]
@simon3z I have built it (from my repo: https://hub.docker.com/r/efreiber/image-inspector/builds/bkuvrv5zxxec5rhyulty4ce/) and tested it with the proposed PR in ManageIQ to get successful scans on systems with the new "docker-pullable" version.

**Pull request merged**
