### PR TITLE
Use `dep` to manage dependencies

### PR DESCRIPTION
**Pull request by jhernand**
Currently the image inspector uses the `trash` tool to manage the
dependencies, using the `vendor.conf` file to declare them, and
commiting `vendor` directory to the source code repository.

This patch changes the project to use the `dep` tool and removes the
`vendor` directory from the source code repository. The dependencies
will be downloaded by the `dep` tool when running `make`.

### CODE REVIEW

**Comment by enoodle** [comment]
@jhernand what are the benefits of commiting the file `Gopkg.lock` ?
Seems like it is changed by `dep ensure` when the unconstrained dependencies are updated. It is similar to me to a `Gemfile.lock`.

**Comment by jhernand** [comment]
The advantage of having the `Gopkg.lock` file in the repository is that if you use `dep ensure -vendor-only` then it will get exactly the versions dependencies that you have listed in that file. Note that in the `Makefile` we are using that `-vendor-only` option, so the unconstrained dependencies will not be updated. Only if you run `dep ensure` manually will they be updated.

**Review by enoodle — APPROVED** [review]
I am very much for this,
When we moved to trash there was no clear standard but `dep` seems to be it now.
Also, not including `vendor` directory is a nice move in my opinion. It will be lighter repository and clearer for PRs that are adding/changing dependencies.

**Comment by jhernand** [comment]
My understanding from #68 and from how `dep` works is that it downloads more dependencies because it doesn't ignore tests. That means that after this patch there will be still much more files in the the `vendor` directory when using `dep` than when using `trash`. But note that the patch also changes the project so that the `vendor` directory will not be committed into the git repository, so it drastically reduces the size of the working copy (not of the repository itself, as old `vendor` contents will still be in the history).

As for #85, I think it will actually improve it a lot; the commit will go from 912 changed files to less than 20, which is good for review, for example.

**Comment by enoodle** [comment]
We can also change the way that we build the container image to not copy the whole project and build it on the image, but create the binary file locally and only copy that.
It will create smaller images as they won't need the golang compilers installed and will ignore the added files that dep is coping.  This is the way that Prometheus is building the container image.

**Comment by jhernand** [comment]
Indeed, actually I wanted to do exactly that, and this was the first step.

**Comment by enoodle** [comment]
@jhernand I think I learned of this option from you and from @zgalor

**Comment by zgalor** [comment]
:+1: for dep.
Regarding building the binary outside of the Dockerfile, This will probably break docker hub auto-build

**Comment by jhernand** [comment]
To overcome the problem with the docker hub auto-build we could maybe modify the Travis configuration so that it builds and *pushes* the image to docker hub.

**Comment by simon3z** [comment]
> As for #85, I think it will actually improve it a lot; the commit will go from 912 changed files to less than 20, which is good for review, for example.

Nice! :+1: 
@jhernand do you want to queue this after #91 ?

**Comment by enoodle** [comment]
ping @jhernand Can you rebase this on the changes from #91 please?

**Pull request closed without merging**
