### PR TITLE
downgrading webdav to db8e4de5

### PR DESCRIPTION
**Pull request by enoodle**
This is a downgrade to the original version that was in use in image-inspector and
had (among many other thing) a different handling for directories.
full hash db8e4de5b2d6653f66aea53094624468caad15d2

[1] https://github.com/openshift/image-inspector/compare/master...enoodle:downgrade_webdav#diff-d160bfb9c99c28cfdee527c545ae524cL211

### CODE REVIEW

**Comment by jhernand** [comment]
Looks good. Can you explain (in the commit message) why is the downgrade needed?

**Comment by simon3z** [comment]
@enoodle have you verified the fix? (built and tested/verified that it's working correctly with old/existing clients)

**Comment by enoodle** [comment]
@simon3z Yes, I have built it and tested against ManageIQ. This allowed ManageIQ to read the packages from the image. I also checked against cadaver and it could read from both versions

**Comment by simon3z** [comment]
@jhernand are you OK with the commit message?
I think there is at least a typo and I am not sure if we want to mention ManageIQ so explicitly, anyway let me know with a `LGTM` when it's OK for you.

**Comment by jhernand** [comment]
I would like to see a reference to a ManageIQ issue, if it exists. Other than that it looks good to me. I think that mentioning ManageIQ isn't bad; it is the reason for the change, so why not mention it explicitly?

**Comment by enoodle** [comment]
I have created an issue to log this: https://github.com/ManageIQ/manageiq-smartstate/issues/51
Do you think it should be in the commit message?

**Comment by jhernand** [comment]
Yes, please, add that link to the commit message.

**Comment by simon3z** [comment]
> I would like to see a reference to a ManageIQ issue, if it exists. Other than that it looks good to me. I think that mentioning ManageIQ isn't bad; it is the reason for the change, so why not mention it explicitly?

@jhernand image-inspector is an openshift project and fully independent from ManageIQ bugs.

In fact we are downgrading here because the change is non backward-compatible not because ManageIQ didn't use `PROPFIND`.

**Comment by simon3z** [comment]
> Yes, please, add that link to the commit message.

@jhernand linking the issue "Use PROPFIND to test for file existence in Webdav https://github.com/ManageIQ/manageiq-smartstate/issues/51" is really misleading, how is going to help anyone using image-inspector?

**Comment by jhernand** [comment]
The `image-inspector` It is not fully independent of its users, therefore not fully independent of ManageIQ. The proof is that we are doing this change to solve a problem for one of the users.

I believe we should document why we do changes, that is what commit messages are for.

That link helps me (maybe not others) understand why this change is needed. If we are concerned about misunderstandings, then we should improve the commit message to address that concern. For example:

```
This change is needed because ManageIQ can't work correctly with
the new implementation of WebDAV including in the version of the
dependency. That ManageIQ problem has been reported here:

  https://github.com/ManageIQ/manageiq-smartstate/issues/51

Once that is fixed in ManageIQ, this change can be reverted.
```

**Comment by enoodle** [comment]
I changed the commit message using juan's suggestion.

**Comment by simon3z** [comment]
PR comment now contains:
> This change is needed because ManageIQ can't work correctly with
> the new implementation of WebDAV including in the version of the
> dependency. That ManageIQ problem has been reported here:
> 
>   ManageIQ/manageiq-smartstate#51
> 
> Once that is fixed in ManageIQ, this change can be reverted.

Definitely not the reason why we want to merge this, nor it complies with the spirit of this project.
We're merging this to be backward-compatible not because a client has a faulty implementation for which there is a proper fix.

**Comment by enoodle** [comment]
@simon3z I changed the commit message again to not mention ManageIQ.

**Pull request merged**
