### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by enoodle**
Resubmitting @pweil- patch to this repository. With the new commits we could really use CI support.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
This Bash migration from Origin scripts looks to be pretty old ... I think we've moved forward quite a lot since then and if we move Bash into this repo (instead of creating a common utility/contrib for our org) we should try our best to keep things in sync, especially when they're doing such similar things.

**Comment by deads2k** [comment]
> This Bash migration from Origin scripts looks to be pretty old ... I think we've moved forward quite a lot since then and if we move Bash into this repo (instead of creating a common utility/contrib for our org) we should try our best to keep things in sync, especially when they're doing such similar things.

Focus.....  Anything we have to set up in travis to have it kick these tests?

**Comment by stevekuznetsov** [comment]
> Anything we have to set up in travis to have it kick these tests?

I believe the two pre-requisites as described in the [startup docs](https://docs.travis-ci.com/user/getting-started/) are:
 - Travis made aware of the repository as owned by the Openshift user (is this Rosie? @danmcp)
 - the `.travis.yml` file present in the root of the `master` branch of the repository

**Comment by danmcp** [comment]
@stevekuznetsov @deads2k Travis is now turned on for this repo.  Next push with a .travis.yml will kick it off.

**Comment by pweil-** [comment]
> This Bash migration from Origin scripts looks to be pretty old

Yeah, this was done quite a while ago so it has sat for a long time and has probably suffered code rot.

**Comment by enoodle** [comment]
@pweil- @stevekuznetsov Do you suggest starting the travis / bash migrations over or trying to stabilize this? I don't have much experience in that but I  want to make it work for this repo. What do you suggest?

**Comment by pweil-** [comment]
If this PR is still working fine then I see no problem with getting it in for the CI support while refactoring to the new tools/structure that @stevekuznetsov has been working on.

**Comment by stevekuznetsov** [comment]
I imagine there's a pretty clean break between things you ported over and didn't touch and stuff you changed to suit this use -- if that's the case, let's try to update the stuff you haven't touched and see how badly things work out.

**Comment by simon3z** [comment]
What's the status on this? This seems really interesting. Can we patch it up to make it working?

**Comment by enoodle** [comment]
For the time being I made it work. I tried coping files from origin/hack/ and using them but `common.sh` and `build-go.sh` were too much for me for the moment. I want to merge this for the time being and then update to the new version without pressure on another PR.

**Comment by enoodle** [comment]
@simon3z ping. The other PRs seem failing because travis can't find `.travis.yaml` that this PR has.

**Pull request merged**
